addons:
  apt:
    packages:
    - nasm

env:
  global:
  - DOCKER_REPO=rootlogin/go-wiki-frontend
  - secure: Y52cQMxYyAwLs2MJg6qL5zCcZnm06X5mVLGcAJoIIJ+yrF1J5ePktuD/vNm51c4UAdIFNpQztveiHNoikwzJQ3lS2/RFUqJXTr+c5b62ZtI26p9WTQDXIHlaD6oRJKX8nvE/wB3LCkLvbH5pPFvyvrXYfewHtB0Glwk8tbiQTjknCczPSJBm8ONy4/D6lZ+B48xiS/jC0J6aALL2DjAt+WzdXbTSuA3L5B59TjnMkOh97Mf+uxwiqYA+w9hHvzZWKyuZ31RkC4aIjcHil3IaqK+94Eg/uCY6ijwu3eJ1oT8EZPHeFjngO9NVNhMlz9muHL1hM3LqK51Ddq/u3JvnhoLIO31QP2KZK4nc8sIjZVvmePOKnuGkabwzhJzQxaXLVwkwpgtp2ZtCV7F439ZtlkXvDaax97TssJkZWuWAs3+dVyMyPnFR65GwVGObpEgriwBUY68n6SorXGf3wpQJ4srCa64DNgImtXbmU8r3HRD2QddlX63bdGlt7vxqWmUgbM5RQLgOXNfhv3Ontas29+WhAczvXrTZkrvoQBmymzZI/boQXBg9KswrFs9GLQqlBgH7UZhyroIuByfvYTJ05DyE+2VXzw/Rwp2qekcyq20ugDgrhVlphDYCjv4kb5uWFG02DFhZV9/2lr3HCG/mn4BmczpzwPrfOtfelox+qP0=

jobs:
  include:
  - language: go
    go: 1.10.x
    node_js: lts/*
    cache:
      directories:
      - node_modules
      - vendor

    before_script:
    - npm install -g npm
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - go get -u github.com/go-bindata/go-bindata/...

    install:
    - # skip

    script:
    - make web_app go_plugin

    deploy:
      - provider: script
        script: curl -T "frontend_plugin" -u "rootlogin:$BINTRAY_API_KEY" -H "X-Bintray-Publish:1" -H "X-Bintray-Package:frontend" -H "X-Bintray-Version:latest-$(date +%Y-%m-%d)" -H "X-Bintray-Override:1" "https://api.bintray.com/content/rootlogin/go-wiki-plugins/latest-$(date +%Y-%m-%d)/frontend_plugin"
        skip_cleanup: true
        on:
          branch: master

      - provider: script
        script: curl -T "frontend_plugin" -u "rootlogin:$BINTRAY_API_KEY" -H "X-Bintray-Publish:1" -H "X-Bintray-Package:frontend" -H "X-Bintray-Version:$TRAVIS_TAG" -H "X-Bintray-Override:1" "https://api.bintray.com/content/rootlogin/go-wiki-plugins/$TRAVIS_TAG/frontend_plugin"
        skip_cleanup: true
        on:
          tags: true

  - language: go
    go: 1.10.x
    sudo: required
    if: (tag =~ ^v) OR (branch IN (master, develop))
    services:
    - docker
    script:
    - export DOCKER_TAG=$(if [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_BRANCH; fi)
    - docker build -t $DOCKER_REPO:$DOCKER_TAG .
