addons:
  apt:
    packages:
    - nasm
env:
  global:
  - "REPO=rootlogin/go-wiki-frontend"

jobs:
  include:
  - language: go

    go: "1.10.x"
    node_js: "lts/*"

    cache:
      directories:
      - node_modules
      - vendor

    before_script:
    - "npm install -g npm"
    - "curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh"
    - "go get -u github.com/go-bindata/go-bindata/..."

    install:
    - # skip

    script:
    - "make web_app go_plugin"

  - sudo: required

    services:
    - docker

    script:
    - 'export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`'
    - 'docker build -t $REPO:$TAG .'