addons:
  apt:
    packages:
    - nasm

jobs:
  include:
  - language: go

    go: "1.10.x"
    node_js: "lts/*"

    cache:
      directories:
      - node_modules
      - vendor

    before_script:
    - "npm install -g npm"
    - "curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh"
    - "go get -u github.com/go-bindata/go-bindata/..."

    install:
    - # skip

    script:
    - "make web_app go_plugin"

  - sudo: required

    services:
    - docker

    script:
    - "docker build -t rootlogin/go-wiki-frontend ."