[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-plugin"

[[constraint]]
  branch = "master"
  name = "github.com/chrootlogin/go-wiki-plugin-sdk"
